-- ==========================================================
-- SUPABASE ADMIN HUB SCHEMA EXTENSION
-- Adds 12 new tables + column extensions for Secure Admin Hub
-- Run this AFTER the base init script. All additive, non-destructive.
-- ==========================================================

-- ========== COLUMN EXTENSIONS TO EXISTING TABLES ==========

-- Products: Add inventory & vendor fields
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS batch_number TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS low_stock_threshold INTEGER DEFAULT 10;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS vendor_id BIGINT;

-- Product Variants: Add MRP price
ALTER TABLE public.product_variants ADD COLUMN IF NOT EXISTS mrp_price DECIMAL(10,2) DEFAULT 0;

-- Reviews: Add pinning + media
ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS media_urls TEXT[] DEFAULT '{}';
ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN DEFAULT FALSE;

-- Orders: Add logistics & returns fields
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS return_reason TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS refund_status TEXT DEFAULT 'none' CHECK (refund_status IN ('none','requested','approved','refunded','rejected'));
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS courier_partner TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS dispatch_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS awb_number TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS estimated_delivery DATE;

-- ========== NEW TABLES ==========

-- 1. Inventory Logs
CREATE TABLE IF NOT EXISTS public.inventory_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  variant_id BIGINT REFERENCES public.product_variants(id) ON DELETE SET NULL,
  change_type TEXT NOT NULL CHECK (change_type IN ('restock','sale','adjustment','return','damage')),
  quantity_change INTEGER NOT NULL,
  batch_number TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Vendors
CREATE TABLE IF NOT EXISTS public.vendors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact_person TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  gst_number TEXT,
  vendor_type TEXT DEFAULT 'supplier' CHECK (vendor_type IN ('supplier','printer','logistics','packaging')),
  is_active BOOLEAN DEFAULT TRUE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Vendor Products (procurement pricing)
CREATE TABLE IF NOT EXISTS public.vendor_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id BIGINT REFERENCES public.vendors(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  procurement_price DECIMAL(10,2),
  last_ordered DATE,
  quantity_ordered INTEGER DEFAULT 0,
  notes TEXT,
  UNIQUE(vendor_id, product_id)
);

-- 4. Support Tickets
CREATE TABLE IF NOT EXISTS public.support_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  subject TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'open' CHECK (status IN ('open','in_progress','resolved','closed')),
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('low','medium','high','urgent')),
  category TEXT DEFAULT 'general',
  assigned_to TEXT,
  sla_deadline TIMESTAMP WITH TIME ZONE,
  resolved_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. SEO Metadata
CREATE TABLE IF NOT EXISTS public.seo_metadata (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_path TEXT UNIQUE NOT NULL,
  meta_title TEXT,
  meta_description TEXT,
  keywords TEXT[],
  og_image TEXT,
  canonical_url TEXT,
  robots TEXT DEFAULT 'index,follow',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. Reports Cache
CREATE TABLE IF NOT EXISTS public.reports_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_type TEXT NOT NULL,
  report_data JSONB,
  date_range_start DATE,
  date_range_end DATE,
  generated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. WhatsApp Campaigns (Jerry AI)
CREATE TABLE IF NOT EXISTS public.whatsapp_campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  product_name TEXT,
  target_audience TEXT,
  campaign_goal TEXT,
  tone TEXT DEFAULT 'professional',
  campaign_message TEXT,
  hook TEXT,
  cta TEXT,
  variations JSONB,
  scratchpad_notes TEXT,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft','scheduled','sent')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 8. Credentials Vault
CREATE TABLE IF NOT EXISTS public.credentials_vault (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  service_name TEXT NOT NULL,
  username TEXT,
  encrypted_value TEXT NOT NULL,
  category TEXT DEFAULT 'api_key' CHECK (category IN ('api_key','password','token','secret','other')),
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 9. Social Posts
CREATE TABLE IF NOT EXISTS public.social_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform TEXT NOT NULL CHECK (platform IN ('instagram','facebook','twitter','whatsapp','youtube')),
  content TEXT NOT NULL,
  media_url TEXT,
  scheduled_at TIMESTAMP WITH TIME ZONE,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft','scheduled','posted','failed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 10. Analytics Events
CREATE TABLE IF NOT EXISTS public.analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  event_data JSONB,
  page_path TEXT,
  user_agent TEXT,
  ip_address TEXT,
  user_id UUID,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 11. Invoices
CREATE TABLE IF NOT EXISTS public.invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
  invoice_number TEXT UNIQUE NOT NULL,
  customer_name TEXT,
  customer_email TEXT,
  billing_address TEXT,
  items JSONB,
  subtotal DECIMAL(10,2),
  tax DECIMAL(10,2) DEFAULT 0,
  total DECIMAL(10,2),
  notes TEXT,
  is_custom BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 12. Shipping Partners
CREATE TABLE IF NOT EXISTS public.shipping_partners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact_person TEXT,
  phone TEXT,
  email TEXT,
  tracking_url_template TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 13. Customer Enquiries
CREATE TABLE IF NOT EXISTS public.enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  subject TEXT,
  message TEXT NOT NULL,
  status TEXT DEFAULT 'new' CHECK (status IN ('new','read','replied','closed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ========== INDEXES ==========
CREATE INDEX IF NOT EXISTS idx_inventory_logs_product ON public.inventory_logs(product_id);
CREATE INDEX IF NOT EXISTS idx_vendor_products_vendor ON public.vendor_products(vendor_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON public.support_tickets(status);
CREATE INDEX IF NOT EXISTS idx_analytics_events_type ON public.analytics_events(event_type);
CREATE INDEX IF NOT EXISTS idx_analytics_events_created ON public.analytics_events(created_at);
CREATE INDEX IF NOT EXISTS idx_invoices_order ON public.invoices(order_id);

-- ========== RLS (permissive for admin use) ==========
ALTER TABLE public.inventory_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credentials_vault ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read/write (admin enforced at app level)
CREATE POLICY "Admin full access inventory_logs" ON public.inventory_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin full access vendors" ON public.vendors FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin full access support_tickets" ON public.support_tickets FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin full access credentials_vault" ON public.credentials_vault FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin full access invoices" ON public.invoices FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin full access shipping_partners" ON public.shipping_partners FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin full access seo_metadata" ON public.seo_metadata FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin full access whatsapp_campaigns" ON public.whatsapp_campaigns FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin full access social_posts" ON public.social_posts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin full access analytics_events" ON public.analytics_events FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin full access reports_cache" ON public.reports_cache FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin full access vendor_products" ON public.vendor_products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Admin full access enquiries" ON public.enquiries FOR ALL USING (true) WITH CHECK (true);
