-- ==========================================================
-- HONEYPOT + SECURE ADMIN SETUP
-- ==========================================================

-- 1. Create phishing_attempts table to log honeypot entries
CREATE TABLE IF NOT EXISTS public.phishing_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entered_email TEXT,
  entered_password TEXT,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.phishing_attempts ENABLE ROW LEVEL SECURITY;

-- Only admins can read phishing attempts
CREATE POLICY "Admins can view phishing attempts" ON public.phishing_attempts
FOR SELECT TO authenticated
USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- Anyone can insert (the honeypot needs to work for unauthenticated users too)
CREATE POLICY "Anyone can insert phishing attempts" ON public.phishing_attempts
FOR INSERT WITH CHECK (true);

-- 2. Create secure admin user masteradmin@oa.online
DO $$
DECLARE
  secure_admin_id uuid := gen_random_uuid();
BEGIN
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'masteradmin@oa.online') THEN
    INSERT INTO auth.users (
      id, instance_id, role, aud, email, raw_app_meta_data, raw_user_meta_data, 
      is_super_admin, encrypted_password, email_confirmed_at, created_at, updated_at
    )
    VALUES (
      secure_admin_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 
      'masteradmin@oa.online', 
      '{"provider":"email","providers":["email"]}', '{"full_name": "Master Admin"}', 
      false, crypt('masteradmin123', gen_salt('bf')), now(), now(), now()
    );
  ELSE
    SELECT id INTO secure_admin_id FROM auth.users WHERE email = 'masteradmin@oa.online';
  END IF;

  INSERT INTO public.profiles (id, full_name, role)
  VALUES (secure_admin_id, 'Master Admin', 'admin')
  ON CONFLICT (id) DO UPDATE SET role = 'admin';
END $$;

-- 3. Also ensure organic.arusuvai@gmail.com is admin
UPDATE public.profiles SET role = 'admin' 
WHERE id IN (SELECT id FROM auth.users WHERE email = 'organic.arusuvai@gmail.com');

INSERT INTO public.profiles (id, full_name, role)
SELECT id, raw_user_meta_data->>'full_name', 'admin'
FROM auth.users WHERE email = 'organic.arusuvai@gmail.com'
ON CONFLICT (id) DO UPDATE SET role = 'admin';

-- 4. Update trigger to auto-assign admin for known emails
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  assigned_role TEXT := 'customer';
BEGIN
  IF (new.email IN ('organic.arusuvai@gmail.com', 'masteradmin@oa.online', 'masteradmin@example.com')) THEN
    assigned_role := 'admin';
  END IF;
  INSERT INTO public.profiles (id, full_name, avatar_url, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', assigned_role)
  ON CONFLICT (id) DO UPDATE SET role = EXCLUDED.role;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ==========================================
-- UPDATE: ADD MRP STRIKETHROUGH VARIANT SUPPORT
-- ==========================================
ALTER TABLE public.product_variants ADD COLUMN IF NOT EXISTS mrp_price DECIMAL(10,2) DEFAULT 0;


-- ==========================================
-- UPDATE: FEEDBACKS PINNING & MEDIA SUPPORT
-- ==========================================
ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS media_urls TEXT[] DEFAULT '{}';
ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN DEFAULT FALSE;
