-- ==========================================================
-- SUPABASE FULL INITIALIZATION SCRIPT (ORGANIC ARUSUVAI)
-- Includes: Tables Setup, Triggers, RLS, and Test Users
-- ==========================================================

-- 1. Enable RLS and Extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. Create Profiles Table (links to auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  phone TEXT,
  role TEXT DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Categories
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  image_url TEXT,
  banner_image_url TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Products
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  base_price DECIMAL(10,2) NOT NULL,
  discount_price DECIMAL(10,2),
  is_featured BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  seo_title TEXT,
  seo_description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Product Variants (e.g. 100g, 250g)
CREATE TABLE IF NOT EXISTS public.product_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  stock INTEGER DEFAULT 0,
  sku TEXT UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. Product Images
CREATE TABLE IF NOT EXISTS public.product_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  alt_text TEXT,
  sort_order INTEGER DEFAULT 0
);

-- 7. Reviews
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id),
  user_name TEXT NOT NULL,
  rating INTEGER DEFAULT 5 CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  is_approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 8. Addresses
CREATE TABLE IF NOT EXISTS public.addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  label TEXT DEFAULT 'Home',
  full_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  address_line1 TEXT NOT NULL,
  address_line2 TEXT,
  city TEXT DEFAULT 'Chennai',
  state TEXT DEFAULT 'Tamil Nadu',
  pincode TEXT NOT NULL,
  is_default BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 9. Orders
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'placed' CHECK (status IN ('placed', 'confirmed', 'processing', 'out_for_delivery', 'delivered', 'cancelled')),
  total DECIMAL(10,2) NOT NULL,
  delivery_address TEXT NOT NULL,
  payment_id TEXT,
  payment_status TEXT DEFAULT 'pending',
  coupon_code TEXT,
  discount_amount DECIMAL(10,2) DEFAULT 0,
  delivery_charge DECIMAL(10,2) DEFAULT 0,
  tracking_url TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 10. Order Items
CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  variant_name TEXT,
  quantity INTEGER DEFAULT 1,
  price DECIMAL(10,2) NOT NULL,
  image_url TEXT
);

-- 11. Wishlist
CREATE TABLE IF NOT EXISTS public.wishlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, product_id)
);

-- RLS Policies (Basic examples, need to be refined)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Function to handle new user creation in auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the function on user creation
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- ==========================================================
-- ADD TEST ACCOUNTS AND DATA
-- ==========================================================

DO $$
DECLARE
  cust_id uuid := gen_random_uuid();
  admin_id uuid := gen_random_uuid();
BEGIN
  -- Insert Customer 1 into auth.users (triggers profile creation)
  INSERT INTO auth.users (
    id, instance_id, role, aud, email, raw_app_meta_data, raw_user_meta_data, 
    is_super_admin, encrypted_password, email_confirmed_at, created_at, updated_at
  )
  VALUES (
    cust_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'customer1@example.com', 
    '{"provider":"email","providers":["email"]}', '{"full_name": "Customer 1"}', 
    false, crypt('customer123', gen_salt('bf')), now(), now(), now()
  );

  -- Set explicit roles
  UPDATE public.profiles SET role = 'customer' WHERE id = cust_id;

  -- Insert Master Admin into auth.users
  INSERT INTO auth.users (
    id, instance_id, role, aud, email, raw_app_meta_data, raw_user_meta_data, 
    is_super_admin, encrypted_password, email_confirmed_at, created_at, updated_at
  )
  VALUES (
    admin_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'masteradmin@example.com', 
    '{"provider":"email","providers":["email"]}', '{"full_name": "Master Admin"}', 
    false, crypt('masteradmin123', gen_salt('bf')), now(), now(), now()
  );

  -- Set Master Admin Role
  UPDATE public.profiles SET role = 'admin' WHERE id = admin_id;

END $$;

-- Insert dummy products
DO $$
DECLARE
  spice_cat_id BIGINT;
  oil_cat_id BIGINT;
BEGIN
  -- Insert Spices Category
  INSERT INTO public.categories (name, slug, description, sort_order)
  VALUES ('Spices', 'spices', 'Organic spices straight from the farm', 1)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
  RETURNING id INTO spice_cat_id;
  
  -- Insert Cold Pressed Oils Category
  INSERT INTO public.categories (name, slug, description, sort_order)
  VALUES ('Cold Pressed Oils', 'cold-pressed-oils', 'Traditional stone-ground oils', 2)
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
  RETURNING id INTO oil_cat_id;

  -- Insert dummy Products
  INSERT INTO public.products (category_id, name, slug, base_price, discount_price, is_featured, is_active)
  VALUES 
    (spice_cat_id, 'Organic Turmeric Powder', 'organic-turmeric-powder', 199.00, 149.00, true, true),
    (oil_cat_id, 'Cold Pressed Coconut Oil', 'cold-pressed-coconut-oil', 449.00, 349.00, true, true),
    (spice_cat_id, 'Organic Black Pepper', 'organic-black-pepper', 279.00, 199.00, true, true),
    (oil_cat_id, 'Groundnut Oil (1L)', 'groundnut-oil-1l', 350.00, 279.00, true, true)
  ON CONFLICT (slug) DO NOTHING;
END $$;
