-- ==========================================
-- ADDING NEW TABLES & SEEDING ACCOUNT DATA
-- ==========================================

-- 1. Create Extra Tables for Swiggy-Like Features
CREATE TABLE IF NOT EXISTS public.coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  description TEXT,
  discount_amount DECIMAL(10,2) DEFAULT 0,
  expiry_date TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS public.user_coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  coupon_id BIGINT REFERENCES public.coupons(id) ON DELETE CASCADE,
  UNIQUE(user_id, coupon_id)
);

CREATE TABLE IF NOT EXISTS public.saved_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  card_type TEXT,
  last_four TEXT,
  cardholder_name TEXT
);

-- 2. Seed Data for Customer 1
DO $$
DECLARE
  cust_id UUID;
  spices_id BIGINT;
  oils_id BIGINT;
  order1_id BIGINT;
  order2_id BIGINT;
  coupon1_id BIGINT;
  coupon2_id BIGINT;
BEGIN
  -- Get Customer 1's ID from auth
  SELECT id INTO cust_id FROM auth.users WHERE email = 'customer1@example.com' LIMIT 1;
  
  IF cust_id IS NULL THEN
     RAISE NOTICE 'Customer 1 not found. Please run the full_init script first.';
     RETURN;
  END IF;

  -- Get Product IDs for seeding
  SELECT id INTO spices_id FROM public.products WHERE slug = 'organic-turmeric-powder' LIMIT 1;
  SELECT id INTO oils_id FROM public.products WHERE slug = 'cold-pressed-coconut-oil' LIMIT 1;

  -- Insert Saved Address
  INSERT INTO public.addresses (user_id, label, full_name, phone, address_line1, city, state, pincode, is_default)
  VALUES (cust_id, 'Home', 'Customer 1', '+91 9876543210', '123 Anna Nagar, 4th Street', 'Chennai', 'Tamil Nadu', '600040', true);

  -- Insert Orders (Swiggy Logic)
  INSERT INTO public.orders (user_id, status, total, delivery_address, payment_status, created_at)
  VALUES (cust_id, 'delivered', 647.00, '123 Anna Nagar, 4th Street, Chennai', 'paid', now() - INTERVAL '3 days')
  RETURNING id INTO order1_id;

  INSERT INTO public.orders (user_id, status, total, delivery_address, payment_status, created_at)
  VALUES (cust_id, 'out_for_delivery', 349.00, '123 Anna Nagar, 4th Street, Chennai', 'pending', now() - INTERVAL '4 hours')
  RETURNING id INTO order2_id;

  -- Insert Order Items
  IF spices_id IS NOT NULL THEN
    INSERT INTO public.order_items (order_id, product_id, variant_name, quantity, price)
    VALUES (order1_id, spices_id, '250g', 2, 149.00);
  END IF;

  IF oils_id IS NOT NULL THEN
    INSERT INTO public.order_items (order_id, product_id, variant_name, quantity, price)
    VALUES (order1_id, oils_id, '500ml', 1, 349.00);

    INSERT INTO public.order_items (order_id, product_id, variant_name, quantity, price)
    VALUES (order2_id, oils_id, '500ml', 1, 349.00);
    
    -- Insert out-of-stock wishlist logic
    UPDATE public.products SET is_active = false WHERE id = oils_id; -- Make oil out of stock for testing wishlist
    INSERT INTO public.wishlist (user_id, product_id) VALUES (cust_id, oils_id);
    INSERT INTO public.wishlist (user_id, product_id) VALUES (cust_id, spices_id);
  END IF;

  -- Insert Coupons
  INSERT INTO public.coupons (code, description, expiry_date) VALUES ('SPRING20', 'Flat 20% off on Spices', now() + INTERVAL '30 days') RETURNING id INTO coupon1_id;
  INSERT INTO public.coupons (code, description, expiry_date) VALUES ('FREEDEL', 'Free Delivery > ₹500', now() + INTERVAL '14 days') RETURNING id INTO coupon2_id;

  INSERT INTO public.user_coupons (user_id, coupon_id) VALUES (cust_id, coupon1_id), (cust_id, coupon2_id);

  -- Insert Saved Payment
  INSERT INTO public.saved_payments (user_id, card_type, last_four, cardholder_name) VALUES (cust_id, 'HDFC Bank Credit Card', '4321', 'Customer One');

END $$;
